### ISSUE TITLE
Test Driven Development coverage

### ISSUE THREAD

**Issue by doyu** [Origami-TinyML/tflm_hello_world#16]
Present unit test code coverage

**Comment by doyu** [comment]
Any update?

**Comment by ArttuLe** [comment]
@doyu #16

```
FROM ubuntu

RUN apt update && apt install -y git make unzip curl g++ python3 pip wget
COPY /build/requirements.txt ./
RUN pip3 install -r requirements.txt
RUN git clone https://github.com/tensorflow/tflite-micro.git

WORKDIR tflite-micro

RUN make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test hello_world_bin ADDITIONAL_DEFINES=--coverage
RUN gcov -pb -o gen/linux_x86_64_default/obj/core/tensorflow/lite/micro/examples/hello_world tensorflow/lite/micro/examples/hello_world/hello_world_test.cc

#Move the generated .gcov file to the Host machine

CMD `["./gen/linux_x86_64_default/bin/hello_world"]

```
- Dockerfile to generate code coverage.
- gcov -pb -o -command generates the .gcov files for code coverage, which would need to be transferred from inside the container to the host machine for uploading.
- In the workflow (.i.e, hostmachine) "Github and Codecov" -section: https://about.codecov.io/blog/how-to-set-up-codecov-with-c-and-github-actions/

**Comment by doyu** [comment]
@ArttuLe Could you send a PR? I won't take but it's easier for me to try, I guess.....

**Comment by doyu** [comment]
@ArttuLe 

I'm sorry and I am lost at which issue you implemented a codecov bad badge. Still I don't see that badge on the repo site after I merged a small change in READEME.md. Does the codecov baget show up only when C-code is modified?
