### ISSUE TITLE
Task 2 adding unit test code coverage for *.ipynb files.

### ISSUE THREAD

**Issue by lifeofborna** [Origami-TinyML/tflm_hello_world#35]
I have recently been exploring the use of nbdev and Jupyter Notebooks. I attempted to add nbdev to my repository, but I am unsure if I have done so correctly. 

My fork of the repository can be found here: https://github.com/lifeofborna/tflm_hello_world. 

I am now wondering which specific .ipynb files are meant by "Add unit test code coverage for *.ipynb files." I would greatly appreciate any tips or suggestions on how to properly add nbdev to my repository, and how to proceed with adding code coverage for the .ipynb files. Thank you.

**Comment by doyu** [comment]
Merging this into the original one.
