### ISSUE TITLE
WebApp install a TinyML model in Hello binary

### ISSUE THREAD

**Issue by doyu** [Origami-TinyML/tflm_hello_world#39]
![Image](https://user-images.githubusercontent.com/3657095/214770146-9ef08e41-ef59-4a55-bd97-1c6453baebf4.png)

# Steps

1. You'll install a TinyML model in Jupyter notebook, named "installing.ipynb", as instructed in TensorFlow lite for micro site
2. "installing.ipynb" should have some tests and documents, which would be processed by nbdev_* commands, https://nbdev.fast.ai/getting_started.html
4. nbdev will convert "installing.ipynb" to "installing.py" automatically.
5. You'll import "installing.py" in "tflm_hello_world/pages/6_instaling.py" as a library
6. You'll implement GUI for this installing in Streamlit toolkit   - You'll list, search, choose a trained model & devices in a csv file via Pandas dataframe, implemented a simple streamlit UI.   - Trigger compiling
   - Show the result of TinyML

Hello is just a dummy use case. You won't need any fancy UI for now. This is just a preparation for the coming real use case.

This is the destination page, https://doyu-tflm-hello-world-tinymlaas-yaz40u.streamlit.app/installing

The simple example, https://github.com/doyu/uoh-software-project-time-report/

**Comment by ArttuLe** [comment]
What does this task mean now, since we're already working on the human detection and not Hello world?

**Comment by doyu** [comment]
Sure, closing this now.
