### ISSUE TITLE
WebApp chooses model from list

### ISSUE THREAD

**Issue by doyu** [Origami-TinyML/tflm_hello_world#52]
The parent issue #45
User stories https://miro.com/app/board/uXjVPwQdIjc=/

## Acceptance test
1. WebApp reads a csv file which holds available models.
2. WebApp shows a list of models.
3. User chooses one of them
4. Visualize the model structure (e.g. https://github.com/lutzroeder/Netron)

**Comment by lifeofborna** [comment]
Hey, where are we supposed to get the CSV file from, and what kind of data it has type and content-wise? Thanks

**Comment by doyu** [comment]
For the time being, you could just locally generate a CSV file stored (git).

**Comment by ArttuLe** [comment]
for visualisation there's a keras/tensorflow oneliner https://pyimagesearch.com/2021/05/22/visualizing-network-architectures-using-keras-and-tensorflow/

**Comment by doyu** [comment]
LGTM

**Comment by doyu** [comment]
FYI: https://discord.com/channels/1062449235729068212/1062449236177854526/1076434355842457630

**Comment by lifeofborna** [comment]
@doyu So do you think its good that we have a models.csv file for example :

Model Name, Model file
Object Detection,/path....
Face detection,/path...
Vibration detection,/path...
anomally detection, / path...

Where Model Name tells us the name of the model and Model File is the path where the model is located in our repository? Is this the point for the csv file?

**Comment by doyu** [comment]
Yes,
`name` could be more unique name for famous NN models (e.g. Yolov6) and 
`path` may be URL on S3 which @nellatuulikki is working on.
