### ISSUE TITLE
Add UI acceptance test in RF

### ISSUE THREAD

**Issue by doyu** [Origami-TinyML/tflm_hello_world#9]
https://github.com/Origami-TinyML/tflm_hello_world/blob/main/README.md#sprint-1

In the detail, https://blog.devgenius.io/testing-streamlit-a1f1fd48ce8f

**Comment by doyu** [comment]
Tuula, this is almost similar to what you are working right now. Can you take this?

**Comment by 2laJ2** [comment]
I have done navigational tests that check that the page changes correctly from the links on the left. I would like to add some more tests now that the first tests (finally) function correctly. Does this task also include writing a new Dockerfile and running the tests from it?

**Comment by doyu** [comment]
> I have done navigational tests that check that the page changes correctly from the links on the left.

Cool!

> Does this task also include writing a new Dockerfile and running the tests from it?

That is a part of 
https://github.com/Origami-TinyML/tflm_hello_world/issues/10, owned by @matiasto

**Comment by doyu** [comment]
It seems to be working now but I encountered a few fail previously with the exact same environment. There might be some timing issue left? Need some more wait? 

![Image](https://user-images.githubusercontent.com/3657095/215717666-53fc6ca6-78a1-45e6-bc30-bc965657d37d.png)

**Comment by doyu** [comment]
Why `python -m coverage report` doesn't work with tflm?

![Image](https://user-images.githubusercontent.com/3657095/215721741-c3313a36-14a9-4987-8dda-016544468337.png)
