### ISSUE TITLE
Demo video

### ISSUE THREAD

**Issue by lifeofborna** [Origami-TinyML/tflm_hello_world#92]
Video demo 8 minutes

We can use The original proposal for this project and help with the text.

Audio by AI? 
Voicebooking (website)
Create a project, Add text then you can select voice language and speed
It might be limited / there should be a workaround, you can't download anymore 
Some editing software like iMovie for mac, 
Placing the audio in the audio track and syncing it with PowerPoint
Export slides png, sync with the audio?
Powerpoint may have functionalities for this
Download an audio fo
Powerpoint recording Can you use the source of the audio (voice booking)?

Video script suggestion:
Spend 3 mins for background, 2 mins for scrum/methodology robot framework, nbdev, and last minute maybe a small demo from the product?

Core things for the demo: 
What has the client asked us, how we have done it software engineering POV, whats the current status? 

Some sources to use the information for the PowerPoint:
[TinyML as a service](https://www.ericsson.com/en/blog/2019/12/tinyml-as-a-service)
[TinyML eco system](https://ieeexplore.ieee.org/abstract/document/9427352)
[Proposal for the project](https://github.com/Origami-TinyML/helsinki/blob/main/soft_eng_proj_tinyml_lifecycle.pdf)

Roberto can give us feedback on the final product.

**Comment by lifeofborna** [comment]
start of may

**Comment by doyu** [comment]
JFYI:
@robertmora will be away next week. It's better to schedule some briefing meeting for video editing from him He's familiar with academic video editing well.

**Comment by robertmora** [comment]
Meeting with the team on Friday morning for discussing how to arrange this.

**Comment by doyu** [comment]
@robertmora, I know you must be extremely busy before the next week bisiness trip. But this meeting would save a lot time to create a demo video, really appreciated!
